### ISSUE TITLE
Could you deploy without Cloudflare?

### ISSUE THREAD

**Issue by hello-smile6** [draeder/signal-swarm#1]
From what I understand, Cloudflare is just a rate-limiting reverse proxy and load balancer.

**Comment by draeder** [comment]
I'm using Cloudflare for DNS TXT records for the domain. The reason for this choice is it's ease of use with the Cloudflare API to insert the DNS TXT records. And it's free.

**Comment by draeder** [comment]
Done! I've moved the repo to: https://github.com/draeder/tracker-swarm
